language: node_js
node_js:
  - "12"
install:
  - npm install # yarn install
script:
  - npm run build # yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 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 # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: main