language: node_js
node_js:
  - "12"
os: linux
cache:
  directories:
    - "node_modules"
install:
  - npm install # yarn install
script:
  - npm run build # yarn docs:build
deploy:
  provider: pages
  strategy: git
  cleanup: false
  local_dir: docs/.vuepress/dist
  token: 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 # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: main